FROM node:24-alpine AS deps
WORKDIR /app
COPY package*.json ./
COPY apps/web/package.json apps/web/package.json
RUN npm install
FROM deps AS build
COPY . .
RUN npm run build -w @autoconnect/web
CMD ["npm","run","start","-w","@autoconnect/web"]
